<?php

$schema['REPD'] = array(
    'Old Ref ID' => array('type' => 'varchar(9)'),
    'Ref ID' => array('type' => 'int'),
    'Record Last Updated (dd/mm/yyyy)' => array('type' => 'varchar(10)'),
    'Operator (or Applicant)' => array('type' => 'varchar(82)'),
    'Site Name' => array('type' => 'varchar(99)'),
    'Technology Type' => array('type' => 'varchar(32)'),
    'Storage Type' => array('type' => 'varchar(33)'),
    'Storage Co-location REPD Ref ID' => array('type' => 'varchar(13)'),
    'Installed Capacity (MWelec)' => array('type' => 'float'),
    'CHP Enabled' => array('type' => 'varchar(3)'),
    'RO Banding (ROC/MWh)' => array('type' => 'float'),
    'FiT Tariff (p/kWh)' => array('type' => 'varchar(5)'),
    'CfD Capacity (MW)' => array('type' => 'float'),
    'CfD Allocation Round' => array('type' => 'varchar(19)'),
    'Turbine Capacity (MW)' => array('type' => 'float'),
    'No. of Turbines' => array('type' => 'int'),
    'Height of Turbines (m)' => array('type' => 'float'),
    'Mounting Type for Solar' => array('type' => 'varchar(13)'),
    'Development Status' => array('type' => 'varchar(30)'),
    'Development Status (short)' => array('type' => 'varchar(27)'),
    'Are they re-applying (New REPD Ref)' => array('type' => 'varchar(19)'),
    'Are they re-applying (Old REPD Ref)' => array('type' => 'varchar(12)'),
    'Address' => array('type' => 'varchar(241)'),
    'County' => array('type' => 'varchar(29)'),
    'Region' => array('type' => 'varchar(20)'),
    'Country' => array('type' => 'varchar(16)'),
    'Post Code' => array('type' => 'varchar(11)'),
    'X-coordinate' => array('type' => 'varchar(11)'),
    'Y-coordinate' => array('type' => 'varchar(11)'),
    'Planning Authority' => array('type' => 'varchar(53)'),
    'Planning Application Reference' => array('type' => 'varchar(33)'),
    'Appeal Reference' => array('type' => 'varchar(28)'),
    'Secretary of State Reference' => array('type' => 'varchar(23)'),
    'Type of Secretary of State Intervention' => array('type' => 'varchar(19)'),
    'Judicial Review' => array('type' => 'varchar(10)'),
    'Offshore Wind Round' => array('type' => 'varchar(4)'),
    'Planning Application Submitted' => array('type' => 'varchar(10)'),
    'Planning Application Withdrawn' => array('type' => 'varchar(10)'),
    'Planning Permission Refused' => array('type' => 'varchar(10)'),
    'Appeal Lodged' => array('type' => 'varchar(10)'),
    'Appeal Withdrawn' => array('type' => 'varchar(10)'),
    'Appeal Refused' => array('type' => 'varchar(10)'),
    'Appeal Granted' => array('type' => 'varchar(10)'),
    'Planning Permission Granted' => array('type' => 'varchar(10)'),
    'Secretary of State - Intervened' => array('type' => 'varchar(10)'),
    'Secretary of State - Refusal' => array('type' => 'varchar(10)'),
    'Secretary of State - Granted' => array('type' => 'varchar(10)'),
    'Planning Permission Expired' => array('type' => 'varchar(10)'),
    'Under Construction' => array('type' => 'varchar(10)'),
    'Operational' => array('type' => 'varchar(10)'),
    'Heat Network Ref' => array('type' => 'int')      
);    